name: Run dbt models

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  dbt-build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      actions: 'read'
      
    steps:
      # Checkout the repository so that a path to the action.yml can be used
      - uses: actions/checkout@v3

      # Authenticate to Google SDK for target-bigquery
      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v2.0.0
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
      # PLVR source is tested after crawling 
      - name: Run dbt models # do not test source plvr
        if: always() # Always run this step even if the prior failed due to no artifact found (this should only take effect if first time running)
        uses: ./
        env:
          TARGET_BIGQUERY_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          MELTANO_DATABASE_URI: sqlite:////github/workspace/meltano.db
          MELTANO_ENVIRONMENT: prod
          PYTHONUNBUFFERED: 1
        with:
          args: |
            meltano invoke dbt-bigquery:deps &&
            meltano invoke dbt-bigquery:build --exclude source:plvr
